In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
%matplotlib inline
from sklearn.linear_model import LinearRegression as LR

# 作業ディレクトリ指定
import os
os.chdir("D:\Study\SIGNATE\お弁当需要予測")

In [2]:
train = pd.read_csv("train.csv")
test = pd.read_csv("test.csv")

In [3]:
test.head(10) # 先頭5行表示

,datetime,week,soldout,name,kcal,remarks,event,payday,weather,precipitation,temperature
0,2014-10-1,水,1,メンチカツ,420.0,NaN,NaN,NaN,雨,0,20.2
1,2014-10-2,木,0,バーベキューチキン,415.0,NaN,NaN,NaN,曇,--,23.9
2,2014-10-3,金,0,豚肉のマスタード焼き,405.0,NaN,NaN,NaN,晴れ,--,28.7
3,2014-10-6,月,1,麻婆春雨,400.0,NaN,NaN,NaN,雨,0.5,21.5
4,2014-10-7,火,0,厚揚げ肉みそ炒め,430.0,NaN,NaN,NaN,晴れ,--,22.1
5,2014-10-8,水,0,完熟トマトのホットカレー,420.0,NaN,NaN,NaN,晴れ,--,23.3
6,2014-10-9,木,0,豚キムチ炒め,435.0,NaN,キャリアアップ支援セミナー,NaN,曇,--,22.5
7,2014-10-10,金,0,ポークカレー,NaN,お楽しみメニュー,NaN,1.0,薄曇,--,26.1
8,2014-10-14,火,0,若鶏梅肉包揚げ,408.0,NaN,NaN,NaN,快晴,--,26.8
9,2014-10-15,水,1,ミックスグリル,450.0,料理長のこだわりメニュー,NaN,NaN,雨,1.5,15.6

In [4]:
test.tail(10) # 最後尾5行表示

,datetime,week,soldout,name,kcal,remarks,event,payday,weather,precipitation,temperature
30,2014-11-14,金,1,エビフライ・エビカツ,427.0,NaN,NaN,NaN,快晴,--,15.8
31,2014-11-17,月,1,野菜ごろごろシチュー,433.0,NaN,NaN,NaN,薄曇,--,14.3
32,2014-11-18,火,1,麻婆豆腐,409.0,NaN,NaN,NaN,快晴,--,16.1
33,2014-11-19,水,0,ベルギー風チキンのクリーム煮,430.0,料理長のこだわりメニュー,NaN,NaN,快晴,--,14.9
34,2014-11-20,木,1,スタミナ炒め,421.0,NaN,NaN,NaN,曇,--,10.5
35,2014-11-21,金,0,ロコモコ丼,NaN,お楽しみメニュー,NaN,NaN,快晴,--,14.9
36,2014-11-25,火,1,なすと挽肉のはさみ揚げ,460.0,NaN,NaN,NaN,雨,1.5,11.4
37,2014-11-26,水,1,鶏肉の治部煮風,415.0,NaN,NaN,NaN,雨,1,9.2
38,2014-11-27,木,0,牛丼風,420.0,NaN,NaN,NaN,快晴,--,15.1
39,2014-11-28,金,0,鶏肉のスイートチリソース,416.0,NaN,NaN,NaN,曇,--,15.3

In [5]:
test.shape # 行数と列数

(40, 11)

In [6]:
trainX = train["temperature"]
y = train["y"]

In [7]:
testX = test["temperature"]

In [8]:
trainX = trainX.values.reshape(-1,1)
testX = testX.values.reshape(-1,1)

In [9]:
model1 = LR()

In [10]:
model1.fit(trainX,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=1, normalize=False)

In [11]:
model1.coef_

array([-2.5023821])

In [12]:
model1.intercept_

134.79948383749922

In [13]:
pred = model1.predict(testX)